<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class FollowsController extends Controller
{
    public function __construct()
    {
        $this->middleWare('auth'); // TODO: Change the autogenerated stub
    }
    public function store(User $user){
            return auth()->user()->following()->toggle($user->profile);
    }
}
